
var WeixinApi=(function(){"use strict";function weixinShareTimeline(data,callbacks){callbacks=callbacks||{};var shareTimeline=function(theData){WeixinJSBridge.invoke('shareTimeline',{"appid":theData.appId?theData.appId:'',"img_url":theData.imgUrl,"link":theData.link,"desc":theData.title,"title":theData.desc,"img_width":"640","img_height":"640"},function(resp){switch(resp.err_msg){case'share_timeline:cancel':callbacks.cancel&&callbacks.cancel(resp);break;case'share_timeline:confirm':case'share_timeline:ok':callbacks.confirm&&callbacks.confirm(resp);break;case'share_timeline:fail':default:callbacks.fail&&callbacks.fail(resp);break;}
    callbacks.all&&callbacks.all(resp);});};WeixinJSBridge.on('menu:share:timeline',function(argv){if(callbacks.async&&callbacks.ready){window["_wx_loadedCb_"]=callbacks.dataLoaded||new Function();if(window["_wx_loadedCb_"].toString().indexOf("_wx_loadedCb_")>0){window["_wx_loadedCb_"]=new Function();}
    callbacks.dataLoaded=function(newData){window["_wx_loadedCb_"](newData);shareTimeline(newData);};callbacks.ready&&callbacks.ready(argv);}else{callbacks.ready&&callbacks.ready(argv);shareTimeline(data);}});}
    function weixinSendAppMessage(data,callbacks){callbacks=callbacks||{};var sendAppMessage=function(theData){WeixinJSBridge.invoke('sendAppMessage',{"appid":theData.appId?theData.appId:'',"img_url":theData.imgUrl,"link":theData.link,"desc":theData.desc,"title":theData.title,"img_width":"640","img_height":"640"},function(resp){switch(resp.err_msg){case'send_app_msg:cancel':callbacks.cancel&&callbacks.cancel(resp);break;case'send_app_msg:confirm':case'send_app_msg:ok':callbacks.confirm&&callbacks.confirm(resp);break;case'send_app_msg:fail':default:callbacks.fail&&callbacks.fail(resp);break;}
        callbacks.all&&callbacks.all(resp);});};WeixinJSBridge.on('menu:share:appmessage',function(argv){if(callbacks.async&&callbacks.ready){window["_wx_loadedCb_"]=callbacks.dataLoaded||new Function();if(window["_wx_loadedCb_"].toString().indexOf("_wx_loadedCb_")>0){window["_wx_loadedCb_"]=new Function();}
        callbacks.dataLoaded=function(newData){window["_wx_loadedCb_"](newData);sendAppMessage(newData);};callbacks.ready&&callbacks.ready(argv);}else{callbacks.ready&&callbacks.ready(argv);sendAppMessage(data);}});}
    function weixinShareWeibo(data,callbacks){callbacks=callbacks||{};var shareWeibo=function(theData){WeixinJSBridge.invoke('shareWeibo',{"content":theData.desc,"url":theData.link},function(resp){switch(resp.err_msg){case'share_weibo:cancel':callbacks.cancel&&callbacks.cancel(resp);break;case'share_weibo:confirm':case'share_weibo:ok':callbacks.confirm&&callbacks.confirm(resp);break;case'share_weibo:fail':default:callbacks.fail&&callbacks.fail(resp);break;}
        callbacks.all&&callbacks.all(resp);});};WeixinJSBridge.on('menu:share:weibo',function(argv){if(callbacks.async&&callbacks.ready){window["_wx_loadedCb_"]=callbacks.dataLoaded||new Function();if(window["_wx_loadedCb_"].toString().indexOf("_wx_loadedCb_")>0){window["_wx_loadedCb_"]=new Function();}
        callbacks.dataLoaded=function(newData){window["_wx_loadedCb_"](newData);shareWeibo(newData);};callbacks.ready&&callbacks.ready(argv);}else{callbacks.ready&&callbacks.ready(argv);shareWeibo(data);}});}
    function weixinGeneralShare(data,callbacks){callbacks=callbacks||{};var generalShare=function(general,theData){if(general.shareTo=='timeline'){var title=theData.title;theData.title=theData.desc||title;theData.desc=title;}
        general.generalShare({"appid":theData.appId?theData.appId:'',"img_url":theData.imgUrl,"link":theData.link,"desc":theData.desc,"title":theData.title,"img_width":"640","img_height":"640"},function(resp){switch(resp.err_msg){case'general_share:cancel':callbacks.cancel&&callbacks.cancel(resp,general.shareTo);break;case'general_share:confirm':case'general_share:ok':callbacks.confirm&&callbacks.confirm(resp,general.shareTo);break;case'general_share:fail':default:callbacks.fail&&callbacks.fail(resp,general.shareTo);break;}
            callbacks.all&&callbacks.all(resp,general.shareTo);});};WeixinJSBridge.on('menu:general:share',function(general){if(callbacks.async&&callbacks.ready){window["_wx_loadedCb_"]=callbacks.dataLoaded||new Function();if(window["_wx_loadedCb_"].toString().indexOf("_wx_loadedCb_")>0){window["_wx_loadedCb_"]=new Function();}
        callbacks.dataLoaded=function(newData){window["_wx_loadedCb_"](newData);generalShare(general,newData);};callbacks.ready&&callbacks.ready(general,general.shareTo);}else{callbacks.ready&&callbacks.ready(general,general.shareTo);generalShare(general,data);}});}
    function addContact(appWeixinId,callbacks){callbacks=callbacks||{};WeixinJSBridge.invoke("addContact",{webtype:"1",username:appWeixinId},function(resp){var success=!resp.err_msg||"add_contact:ok"==resp.err_msg||"add_contact:added"==resp.err_msg;if(success){callbacks.success&&callbacks.success(resp);}else{callbacks.fail&&callbacks.fail(resp);}})}
    function imagePreview(curSrc,srcList){if(!curSrc||!srcList||srcList.length==0){return;}
        WeixinJSBridge.invoke('imagePreview',{'current':curSrc,'urls':srcList});}
    function showOptionMenu(){WeixinJSBridge.call('showOptionMenu');}
    function hideOptionMenu(){WeixinJSBridge.call('hideOptionMenu');}
    function showToolbar(){WeixinJSBridge.call('showToolbar');}
    function hideToolbar(){WeixinJSBridge.call('hideToolbar');}
    function getNetworkType(callback){if(callback&&typeof callback=='function'){WeixinJSBridge.invoke('getNetworkType',{},function(e){callback(e.err_msg);});}}
    function closeWindow(){WeixinJSBridge.call("closeWindow");}
    function wxJsBridgeReady(readyCallback){if(readyCallback&&typeof readyCallback=='function'){var Api=this;var wxReadyFunc=function(){readyCallback(Api);};if(typeof window.WeixinJSBridge=="undefined"){if(document.addEventListener){document.addEventListener('WeixinJSBridgeReady',wxReadyFunc,false);}else if(document.attachEvent){document.attachEvent('WeixinJSBridgeReady',wxReadyFunc);document.attachEvent('onWeixinJSBridgeReady',wxReadyFunc);}}else{wxReadyFunc();}}}
    function openInWeixin(){return/MicroMessenger/i.test(navigator.userAgent);}
    return{version:"2.1",ready:wxJsBridgeReady,shareToTimeline:weixinShareTimeline,shareToWeibo:weixinShareWeibo,shareToFriend:weixinSendAppMessage,generalShare:weixinGeneralShare,addContact:addContact,showOptionMenu:showOptionMenu,hideOptionMenu:hideOptionMenu,showToolbar:showToolbar,hideToolbar:hideToolbar,getNetworkType:getNetworkType,imagePreview:imagePreview,closeWindow:closeWindow,openInWeixin:openInWeixin};})();